language: c
notifications:
    email: false

before_install:
    - pip install --user codecov

#script: make
script: 
    - ./run.sh

after_success:
    - codecov
    - bash <(curl -s https://codecov.io/bash)
